import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import api, { errorMessage } from '../api/client'

export function AdminDashboard() {
  const [venues, setVenues] = useState([]); const [error, setError] = useState('')
  const load = () => api.get('/api/admin/venues').then((r) => setVenues(r.data)).catch((e) => setError(errorMessage(e)))
  useEffect(load, [])
  const remove = async (id) => { if (!window.confirm('Delete this venue?')) return; try { await api.delete(`/api/admin/venues/${id}`); load() } catch (e) { setError(errorMessage(e)) } }
  return <div><div className="mb-6 flex items-center justify-between"><div><h1 className="page-title">Venues</h1><p className="mt-1 text-sm text-gray-600">Manage venues, categories, and seating layouts.</p></div><Link className="btn" to="/admin/venues/new">Create venue</Link></div>{error && <p className="error mb-4">{error}</p>}<div className="overflow-x-auto border border-gray-200"><table><thead><tr><th>Name</th><th>Address</th><th>Grid</th><th>Seats</th><th /></tr></thead><tbody>{venues.map((v) => <tr key={v.id}><td className="font-semibold">{v.name}</td><td>{v.address}</td><td>{v.rows} × {v.columns}</td><td>{v.seats.length}</td><td className="space-x-3 text-right"><Link className="text-amber-700 underline" to={`/admin/venues/${v.id}/edit`}>Edit</Link><Link className="text-amber-700 underline" to={`/admin/venues/${v.id}/layout`}>Layout</Link><button className="text-red-700 underline" onClick={() => remove(v.id)}>Delete</button></td></tr>)}</tbody></table></div></div>
}

export function VenueFormPage() {
  const { venueId } = useParams(); const editing = Boolean(venueId); const navigate = useNavigate()
  const [form, setForm] = useState({ name: '', address: '', rows: 8, columns: 12, categories: [{name: 'Premium', color_label: '#F59E0B'}, {name: 'Standard', color_label: '#9CA3AF'}] })
  const [newCategory, setNewCategory] = useState(''); const [error, setError] = useState('')
  const load = () => editing && api.get(`/api/admin/venues/${venueId}`).then((r) => setForm(r.data)).catch((e) => setError(errorMessage(e)))
  useEffect(load, [venueId])
  const submit = async (e) => { e.preventDefault(); setError(''); try { if (editing) await api.put(`/api/admin/venues/${venueId}`, {name: form.name, address: form.address, rows: Number(form.rows), columns: Number(form.columns)}); else await api.post('/api/admin/venues', {...form, rows: Number(form.rows), columns: Number(form.columns)}); navigate('/admin') } catch (err) { setError(errorMessage(err)) } }
  const addCategory = async () => { if (!newCategory.trim()) return; try { await api.post(`/api/admin/venues/${venueId}/categories`, {name: newCategory}); setNewCategory(''); load() } catch (e) { setError(errorMessage(e)) } }
  const rename = async (category) => { const name = window.prompt('Category name', category.name); if (!name) return; try { await api.put(`/api/admin/categories/${category.id}`, {name, color_label: category.color_label}); load() } catch (e) { setError(errorMessage(e)) } }
  const removeCategory = async (id) => { try { await api.delete(`/api/admin/categories/${id}`); load() } catch (e) { setError(errorMessage(e)) } }
  return <div className="mx-auto max-w-2xl"><h1 className="page-title">{editing ? 'Edit venue' : 'Create venue'}</h1><form className="panel mt-6 space-y-4" onSubmit={submit}>{error && <p className="error">{error}</p>}<div><label>Venue name</label><input required value={form.name} onChange={(e) => setForm({...form, name: e.target.value})} /></div><div><label>Address</label><textarea required rows="3" value={form.address} onChange={(e) => setForm({...form, address: e.target.value})} /></div><div className="grid grid-cols-2 gap-4"><div><label>Rows</label><input required type="number" min="1" max="100" value={form.rows} onChange={(e) => setForm({...form, rows: e.target.value})} /></div><div><label>Columns</label><input required type="number" min="1" max="200" value={form.columns} onChange={(e) => setForm({...form, columns: e.target.value})} /></div></div>{!editing && <div><label>Seat categories</label>{form.categories.map((c, i) => <div className="mb-2 flex gap-2" key={i}><input required value={c.name} onChange={(e) => setForm({...form, categories: form.categories.map((x, n) => n === i ? {...x, name: e.target.value} : x)})} /><input aria-label="Category color" type="color" className="w-14 p-1" value={c.color_label} onChange={(e) => setForm({...form, categories: form.categories.map((x, n) => n === i ? {...x, color_label: e.target.value} : x)})} /></div>)}<button type="button" className="text-sm text-amber-700 underline" onClick={() => setForm({...form, categories: [...form.categories, {name: '', color_label: '#6B7280'}]})}>Add category</button></div>}{editing && <div><label>Categories</label><div className="space-y-2">{form.categories?.map((c) => <div className="flex items-center justify-between rounded border px-3 py-2 text-sm" key={c.id}><span>{c.name}</span><span className="space-x-3"><button type="button" className="text-amber-700 underline" onClick={() => rename(c)}>Rename</button><button type="button" className="text-red-700 underline" onClick={() => removeCategory(c.id)}>Delete</button></span></div>)}</div><div className="mt-2 flex gap-2"><input placeholder="New category" value={newCategory} onChange={(e) => setNewCategory(e.target.value)} /><button type="button" className="btn-secondary" onClick={addCategory}>Add</button></div></div>}<div className="flex gap-3"><button className="btn">{editing ? 'Save venue' : 'Create venue'}</button><Link className="btn-secondary" to="/admin">Cancel</Link></div></form></div>
}

const rowLabel = (index) => { let value = ''; for (let n = index + 1; n > 0; n = Math.floor((n - 1) / 26)) value = String.fromCharCode(65 + ((n - 1) % 26)) + value; return value }

export function SeatLayoutPage() {
  const { venueId } = useParams(); const navigate = useNavigate(); const [venue, setVenue] = useState(null); const [layout, setLayout] = useState([]); const [error, setError] = useState('')
  useEffect(() => { api.get(`/api/admin/venues/${venueId}`).then((r) => { setVenue(r.data); const byPos = new Map(r.data.seats.map((s) => [`${s.row_label}-${s.seat_number}`, s])); const defaultCategory = r.data.categories[0]?.id; setLayout(Array.from({length: r.data.rows}, (_, row) => Array.from({length: r.data.columns}, (_, col) => byPos.get(`${rowLabel(row)}-${col + 1}`) || {row_label: rowLabel(row), seat_number: col + 1, category_id: defaultCategory, is_active: true})).flat()) }).catch((e) => setError(errorMessage(e))) }, [venueId])
  const update = (index, patch) => setLayout((items) => items.map((item, i) => i === index ? {...item, ...patch} : item))
  const save = async () => { try { await api.post(`/api/admin/venues/${venueId}/seats/bulk`, layout.map(({row_label, seat_number, category_id, is_active}) => ({row_label, seat_number, category_id, is_active}))); navigate('/admin') } catch (e) { setError(errorMessage(e)) } }
  if (!venue) return <p>{error || 'Loading layout…'}</p>
  return <div><div className="mb-6 flex items-center justify-between"><div><h1 className="page-title">{venue.name} seat layout</h1><p className="mt-1 text-sm text-gray-600">Choose each seat’s category. Turn off gaps and unavailable positions.</p></div><button className="btn" onClick={save}>Save layout</button></div>{error && <p className="error mb-4">{error}</p>}<div className="overflow-x-auto panel"><div className="min-w-max space-y-2">{Array.from({length: venue.rows}, (_, row) => <div key={row} className="flex gap-2"><span className="w-7 py-2 text-center text-sm font-semibold">{rowLabel(row)}</span>{layout.slice(row * venue.columns, (row + 1) * venue.columns).map((seat, col) => { const index = row * venue.columns + col; return <div key={col} className={`w-20 rounded border p-1 ${seat.is_active ? 'border-gray-300' : 'border-dashed bg-gray-100 opacity-60'}`}><button className="mb-1 w-full text-xs" onClick={() => update(index, {is_active: !seat.is_active})}>{seat.seat_number} · {seat.is_active ? 'On' : 'Gap'}</button><select className="p-1 text-xs" disabled={!seat.is_active} value={seat.category_id} onChange={(e) => update(index, {category_id: Number(e.target.value)})}>{venue.categories.map((c) => <option value={c.id} key={c.id}>{c.name}</option>)}</select></div>})}</div>)}</div></div></div>
}

