import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import api, { errorMessage } from '../api/client'
import StatusBadge from '../components/StatusBadge'

export function OrganiserDashboard() {
  const [events, setEvents] = useState([]); const [error, setError] = useState('')
  const load = () => api.get('/api/organiser/events').then((r) => setEvents(r.data)).catch((e) => setError(errorMessage(e)))
  useEffect(load, [])
  const remove = async (id) => { if (!window.confirm('Delete this draft event?')) return; try { await api.delete(`/api/organiser/events/${id}`); load() } catch (e) { setError(errorMessage(e)) } }
  return <div><div className="mb-6 flex items-center justify-between"><div><h1 className="page-title">My events</h1><p className="mt-1 text-sm text-gray-600">Create listings and review bookings and revenue.</p></div><Link className="btn" to="/organiser/events/new">Create event</Link></div>{error && <p className="error mb-4">{error}</p>}<div className="overflow-x-auto border border-gray-200"><table><thead><tr><th>Event</th><th>Venue</th><th>Date</th><th>Status</th><th /></tr></thead><tbody>{events.map((event) => <tr key={event.id}><td className="font-semibold">{event.title}</td><td>{event.venue_name}</td><td>{event.show_date} · {event.show_time.slice(0, 5)}</td><td><StatusBadge value={event.status} /></td><td className="space-x-3 text-right"><Link className="text-amber-700 underline" to={`/organiser/events/${event.id}/edit`}>Edit</Link><Link className="text-amber-700 underline" to={`/organiser/events/${event.id}/summary`}>View summary</Link><button className="text-red-700 underline" onClick={() => remove(event.id)}>Delete</button></td></tr>)}</tbody></table></div></div>
}

export function EventFormPage() {
  const { eventId } = useParams(); const editing = Boolean(eventId); const navigate = useNavigate(); const [venues, setVenues] = useState([]); const [error, setError] = useState('')
  const [form, setForm] = useState({venue_id: '', title: '', event_type: 'movie', description: '', show_date: '', show_time: '19:00', status: 'draft', prices: []})
  useEffect(() => { api.get('/api/organiser/venues').then((r) => setVenues(r.data)).catch(() => setError('No venues are available. Ask an admin to create one.')); if (editing) api.get(`/api/organiser/events/${eventId}`).then((r) => setForm({...r.data, show_time: r.data.show_time.slice(0,5)})).catch((e) => setError(errorMessage(e))) }, [eventId])
  const chooseVenue = (id) => { const venue = venues.find((v) => v.id === Number(id)); setForm({...form, venue_id: Number(id), prices: venue?.categories.map((c) => ({category_id: c.id, category_name: c.name, price: ''})) || []}) }
  const submit = async (e) => { e.preventDefault(); try { const payload = {...form, venue_id: Number(form.venue_id), prices: form.prices.map((p) => ({category_id: p.category_id, price: Number(p.price)}))}; if (editing) await api.put(`/api/organiser/events/${eventId}`, payload); else await api.post('/api/organiser/events', payload); navigate('/organiser') } catch (err) { setError(errorMessage(err)) } }
  return <div className="mx-auto max-w-2xl"><h1 className="page-title">{editing ? 'Edit event' : 'Create event'}</h1><form className="panel mt-6 space-y-4" onSubmit={submit}>{error && <p className="error">{error}</p>}<div><label>Title</label><input required value={form.title} onChange={(e) => setForm({...form, title: e.target.value})} /></div><div className="grid grid-cols-2 gap-4"><div><label>Type</label><select value={form.event_type} onChange={(e) => setForm({...form, event_type: e.target.value})}><option value="movie">Movie</option><option value="concert">Concert</option></select></div><div><label>Status</label><select value={form.status} onChange={(e) => setForm({...form, status: e.target.value})}><option value="draft">Draft</option><option value="published">Published</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div></div><div><label>Description</label><textarea required rows="4" value={form.description} onChange={(e) => setForm({...form, description: e.target.value})} /></div><div><label>Venue</label><select required value={form.venue_id} onChange={(e) => chooseVenue(e.target.value)}><option value="">Choose venue</option>{venues.map((v) => <option value={v.id} key={v.id}>{v.name}</option>)}</select></div><div className="grid grid-cols-2 gap-4"><div><label>Date</label><input required type="date" value={form.show_date} onChange={(e) => setForm({...form, show_date: e.target.value})} /></div><div><label>Time</label><input required type="time" value={form.show_time} onChange={(e) => setForm({...form, show_time: e.target.value})} /></div></div><div><label>Per-category pricing</label><div className="space-y-2">{form.prices.map((p, i) => <div key={p.category_id} className="grid grid-cols-[1fr_160px] items-center gap-3"><span className="text-sm">{p.category_name || venues.flatMap((v) => v.categories).find((c) => c.id === p.category_id)?.name}</span><input required min="0.01" step="0.01" type="number" placeholder="Price" value={p.price} onChange={(e) => setForm({...form, prices: form.prices.map((x, n) => n === i ? {...x, price: e.target.value} : x)})} /></div>)}</div></div><div className="flex gap-3"><button className="btn">{editing ? 'Save event' : 'Create event'}</button><Link className="btn-secondary" to="/organiser">Cancel</Link></div></form></div>
}

export function EventSummaryPage() {
  const { eventId } = useParams(); const [data, setData] = useState(null); const [error, setError] = useState('')
  useEffect(() => { api.get(`/api/organiser/events/${eventId}/summary`).then((r) => setData(r.data)).catch((e) => setError(errorMessage(e))) }, [eventId])
  if (!data) return <p>{error || 'Loading summary…'}</p>
  const metrics = [['Total seats', data.total_seats], ['Booked seats', data.booked_seats], ['Available seats', data.available_seats], ['Held seats', data.held_seats], ['Cancelled bookings', data.cancelled_bookings], ['Waitlist', data.waitlist_count]]
  return <div><Link className="text-sm text-gray-600" to="/organiser">← My events</Link><h1 className="page-title mt-4">{data.title} summary</h1><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{metrics.map(([label, value]) => <div className="panel" key={label}><p className="text-sm text-gray-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>)}</div><div className="panel mt-4"><p className="text-sm text-gray-500">Total confirmed revenue</p><p className="mt-1 text-3xl font-bold">₹{data.total_revenue}</p></div></div>
}
